In [1]:
# la ligne suivante charge le package numpy pour accéder aux fonctionnalités
import numpy as np

In [4]:
# Création d'une matrice (3, 2)
A = np.array([ [1, 2], [3, 4], [5, 6]])
print('A =', A) # afficher la matrice A

A = [[1 2]
 [3 4]
 [5 6]]


In [5]:
# afficher les dimensions de A
print('dimensions de A:', A.shape)

dimensions de A: (3, 2)


In [6]:
# Transposée de A
B = A.T
print('B =',B)
print('dimensions de B :', B.shape)

B = [[1 3 5]
 [2 4 6]]
dimensions de B : (2, 3)


In [7]:
# Création d'une matrice B remplie de "1"
C = np.ones((3, 2))

In [9]:
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# addition de A par B
D = A + C
print('C =', C)
print('dimensions de C:', C.shape)

C = [[1. 1.]
 [1. 1.]
 [1. 1.]]
dimensions de C: (3, 2)


In [11]:
# mutiplication de A (3, 2) par B (2, 3)

E = A.dot(B)
print('E =', E)
print('dimensions de E:',E.shape)

E = [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
dimensions de E: (3, 3)
